config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  devise_for :users
  resources :users
  root "static_pages#home"

  get "reviews/show"
  resources :books do
    resources :reviews
  end
  namespace :admin do
    resources :users do
      get "delete"
    end
    resources :books do
      get "delete"
    end
    resources :publishers do
      get "get_publisher"
    end
     resources :authors do
      get "get_author"
    end
  end
  resources :authors, only: %i(index show)
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  belongs_to :category
  has_many :request_details
  has_many :follows
  has_many :likes
  has_many :reviews
  has_many :author_books
  has_many :authors, through: :author_books

  mount_uploader :image, PictureUploader

  delegate :name, to: :category, prefix: :category
  delegate :name, to: :publisher, prefix: :publisher

  scope :newest, ->{order :created_at}
  accepts_nested_attributes_for :author_books

  def writers
    authors.map(&:name).join(", ")
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :get_book, except: %i(index create new)
  before_action :load_books, only: %i(index create update destroy)

  def index; end

  def show; end

  def delete; end

  def new
    @book = Book.new
    @book.author_books.build
  end

  def create
    if @book = Book.create(book_params)
      flash[:success] = t(".msg-create")
    else
      flash[:danger] = t(".msg-error")
    end
    respond_to do |format|
      format.js {}
    end
  end

  def edit; end

  def update
    if @book.update_attributes(book_params)
      flash[:success] = t(".msg-update")
    else
      flash[:danger] = t(".msg-error")
    end
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = t(".msg-destroy")
    else
      flash[:danger] = t(".msg-error")
    end
    respond_to do |format|
      format.js {}
    end
  end

  private

  def load_books
    @search = Book.newest.ransack params[:q]
    @books = @search.result.paginate page: params[:page],
    per_page: Settings.book.per_page
  end

  def get_book
    @book = Book.find_by id: params[:book_id] if params[:book_id].present?
    @book = Book.find_by id: params[:id] if params[:id].present?
    return if @book
    respond_to do |format|
      flash[:danger] = t(".msg-not_found")
      format.js{render partial: "not_found"}
    end
  end

  def book_params
    params.require(:book).permit :category_id, :publisher_id, :name,
      :content, :quantity_of_pages, :publishing_year, :quantity_of_books,
      :image, author_books_attributes: [:id, :author_id, :book_id]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: :show
  authorize_resource
  before_action :load_book, only: :show
  before_action :load_category, only: :index

  def index
    @search = Book.ransack params[:q]
    @books = @search.result.newest.paginate page: params[:page],
      per_page: Settings.book.per_page
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  private

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = t "messenger.no_data"
    render :index
  end

  def load_category
    @category = Category.sort_by_name
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
  def get_name_publisher publisher_id
    Publisher.find_by(id: publisher_id).name
  end

  def select_author
    Author.all.map{|a| [a.name, a.id]}
  end

  def select_category
    Category.all.map{|c| [c.name, c.id]}
  end

  def select_publisher
    Publisher.all.map{|p| [p.name, p.id]}
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def load_categories_selectbox
    @category.map{|u| [u.name, u.id]}
  end

  def number_to_vnd amount
    number_to_currency(amount, unit: I18n.t("books.vnd"),
      precision: Settings.book.number_currency, delimiter: "",
      format: Settings.book.price)
  end
end

app/views/admin/books/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3><%= t ".title" %></h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  <%= t ".msg-comf" %><b><%= @book.name %></b> ?
  </div>
  <div class="modal-footer">
    <%= link_to t(".bnt-yes"), admin_book_path(@book), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to t(".bnt_no"), "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/admin/books/_edit.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h3><%= t(".title") %></h3>
  </div>
</div>
<%= render "form" %>

app/views/admin/books/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for [:admin, @book], remote: true do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="form-group">
          <%= f.label :name, class:"control-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :category, class: "control-label" %>
          <%= f.select :category_id, select_category, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :publisher, class: "control-label" %>
          <%= f.select :publisher_id, select_publisher, class: "form-control" %>
        </div>
        <%= f.fields_for :author_books do |ff| %>
          <div class="form-group">
            <%= ff.label :author, class: "control-label" %>
            <%= ff.select :author_id, select_author, class: "form-control" %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :content, class: "control-label" %>
          <%= f.text_area :content, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :quantity_of_pages, class: "control-label" %>
          <%= f.number_field :quantity_of_pages, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :quantity_of_books, class: "control-label" %>
          <%= f.number_field :quantity_of_books, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :image, class: "control-label" %>
          <%= f.file_field :image, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :publishing_year, class: "control-label" %>
          <%= f.select :publishing_year,
            (Time.zone.now.year - Settings.book.year_max)..(Time.zone.now.year +  Settings.book.year_min) %>
        </div>
    </div>
    <div class="modal-footer">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to t(".bnt-cancel"), "#", class: "btn", data: {dismiss: "modal"} %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/books/_index.html.erb
<% n = 0 %>
<% @books.each do |book| %>
  <tr>
    <td><%= book.id %></td>
    <td><%= book.name %></td>
    <td><%= book.writers %></td>
    <td><%= get_name_publisher book.publisher_id %></td>
    <td><%= book.quantity_of_pages %></td>
    <td><%= book.publishing_year %></td>
    <td><%= book.quantity_of_books %></td>
    <td>
      <%= link_to t(".show"), admin_book_path(book), remote: true %>
      &nbsp;
      <%= link_to t(".edit"), edit_admin_book_path(book), remote: true  %>
      &nbsp;
      <%= link_to t(".delete"), admin_book_delete_path(book), remote: true, class: "delete-user" %>
    </td>
  </tr>
<% end %>

app/views/admin/books/_not_found.js.erb
$('#book-modal').modal('hide')
$('#notification-modal').html('<%= j render "shared/show_notification.html" %>')
$('#notification-div').prepend('<%= j render "shared/flash" %>')
$('#notification-modal').modal('show')

app/views/admin/books/_save.js.erb
$('ul.errors').html('')
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    $('ul.errors').append($('<li />').html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $('#book-modal').modal('hide')
  $('#notification-modal').html('<%= escape_javascript(render "shared/show_notification.html") %>')
  $('#notification-div').prepend('<%= j render "shared/flash" %>')
  $('#notification-modal').modal('show')
  $('#notification-modal').on('hidden.bs.modal', function () {
  location.reload();
  })
<% end %>

app/views/admin/books/delete.js.erb
$('#book-modal').html('<%= j render "delete" %>')
$('#book-modal').modal('show')

app/views/admin/books/edit.js.erb
$('#book-modal').html('<%= j render "edit" %>')
$('#book-modal').modal('show')

app/views/admin/books/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to  new_admin_book_path, remote: true,
      class: "btn btn-primary" do %>
      <span class="glyphicon glyphicon-plus"></span><%= t(".btn-new") %>
    <% end %>
  </div>

  <div class="input-group">
    <%= search_form_for [:admin, @search],class: "navbar-form" do |f| %>
      <%= f.text_field :name_cont, class: "form-control",value: "", placeholder: t(".msg-search_name_book") %>
      <%= f.text_field :publisher_name_cont, class: "form-control",value: "", placeholder: t(".msg-search_name_publisher") %>
      <%= f.text_field :authors_name_cont, class: "form-control",value: "", placeholder: t(".msg-search_name_author") %>
      <div class="input-group-btn">
      <%= button_tag class: "btn btn-default", value: "search" do %>
        <i class="glyphicon glyphicon-search"></i>
      <% end %>
    <% end %>
    </div>
  </div>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th><%= t(".tb-id") %></th>
        <th><%= t(".tb-name") %></th>
        <td><%= t(".tb-autor") %></td>
        <td><%= t(".tb-publisher") %></td>
        <td><%= t(".tb-quantity_of_pages") %></td>
        <td><%= t(".tb-publishing_year") %></td>
        <td><%= t(".tb-quantity_of_books") %></td>
      </tr>
    </thead>
    <tbody class="book-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="book-modal" class="modal fade"></div>
<div id="notification-modal" class=" modal fade"></div>
<%= will_paginate @users %>

app/views/admin/books/new.js.erb
$('#book-modal').html('<%= j (render "new") %>')
$('#book-modal').modal('show')