config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  devise_for :users
  resources :users
  root "static_pages#home"

  get "reviews/show"
  resources :books do
    resources :reviews
  end
  namespace :admin do
    resources :users do
      get "delete"
    end
    resources :books do
      get "delete"
    end
    resources :publishers do
      get "get_publisher"
    end
     resources :authors do
      get "get_author"
    end
  end
  resources :authors, only: %i(index show)
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, [User, Book]
      can :update, User, id: user.id
      can [:create, :read], [Review]
      can :destory, Review do |review|
        review.user == user
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :follows
  has_many :author_books
  has_many :books, through: :author_books

  mount_uploader :avatar, PictureUploader

  scope :newest, ->{order name: :ASC}
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  belongs_to :category
  has_many :request_details
  has_many :follows
  has_many :likes
  has_many :reviews
  has_many :author_books
  has_many :authors, through: :author_books

  mount_uploader :image, PictureUploader

  delegate :name, to: :category, prefix: :category
  delegate :name, to: :publisher, prefix: :publisher

  scope :newest, ->{order :created_at}
  accepts_nested_attributes_for :author_books

  def writers
    authors.map(&:name).join(", ")
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  scope :sort_by_name, ->{order name: :asc}
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :book
  belongs_to :author
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books

  scope :newest, ->{order created_at: :DESC}
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :requests_details
  belongs_to :user

  enum status: {pending: 0, approved: 1, cancel: 2, reject: 3}
end

app/models/request_detail.rb
class RequestDetail < ApplicationRecord
  belongs_to :book
  belongs_to :request

  enum status: {pending: 0, approved: 1, cancel: 2, reject: 3}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user

  delegate :name, to: :user, allow_nil: true

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :request
  has_many :likes
  has_many :reviews
  has_many :follows

  validates :name, presence: true

  enum role: {user: 0, admin: 1}
  enum gender: {male: 0, female: 1}

  scope :newest, ->{order name: :ASC}
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  before_action :load_author, except: %i(index create new)
  before_action :load_authors, only: %i(index create update destroy)

  def index; end

  def show; end

  def get_author; end

  def new
    @author = Author.new
  end

  def create
    if @author = Author.create(author_params)
      flash[:success] = t(".msg-create")
    else
      flash[:danger] = t(".msg-error")
    end
    respond_to do |format|
      format.js {}
    end
  end

  def edit; end

  def update
    if @author.update_attributes(author_params)
      flash[:success] = t(".msg-update")
    else
      flash[:danger] = t(".msg-error")
    end
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    if @author.destroy
      flash[:success] = t(".msg-destroy")
    else
      flash[:danger] = t(".msg-error")
    end
    respond_to do |format|
      format.js {}
    end
  end

  private

  def load_authors
    @search = Author.newest.ransack params[:q]
    @authors = @search.result.paginate page: params[:page],
    per_page: Settings.author.per_page
  end

  def load_author
    @author = Author.find_by id: params[:author_id] if
      params[:author_id].present?
    @author = Author.find_by id: params[:id] if params[:id].present?
    return if @author
    respond_to do |format|
      flash[:danger] = t(".msg-not_found")
      format.js{render partial: "not_found"}
    end
  end

  def author_params
    params.require(:author).permit :name, :profile, :avatar
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
      keys: [:name, :date_of_birth, :gender, :address, :phone])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :load_author, only: :show

  def index
    @search = Author.ransack params[:q]
    @authors = @search.result.newest.paginate page: params[:page],
      per_page: Settings.book.per_page
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  private

  def load_author
    @author = Author.find_by id: params[:id]
    return if @author
    flash[:danger] = t "messenger.no_data"
    render :index
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: :show
  authorize_resource
  before_action :load_book, only: :show
  before_action :load_category, only: :index

  def index
    @search = Book.ransack params[:q]
    @books = @search.result.newest.paginate page: params[:page],
      per_page: Settings.book.per_page
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  private

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = t "messenger.no_data"
    render :index
  end

  def load_category
    @category = Category.sort_by_name
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_review, only: :destroy

  def show
    respond_to do |format|
      format.js
    end
  end

  def create
    @review = Review.new review_params
    if @review.save
      @book = @review.book
      flash[:success] = t "review.successful"
    else
      flash[:danger] = t "review.fails"
    end
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    if @review.destroy
      @book = @review.book
      flash[:success] = t "review.delete"
    else
      flash[:danger] = t "review.fails"
    end
    respond_to do |format|
      format.js {}
    end
  end

  private

  def review_params
    params.require(:review).permit :content, :user_id, :book_id
  end

  def load_review
    @review = Review.find_by id: params[:id]
    return if @review
    flash[:danger] = t "messenger.no_data"
    redirect_to book_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = I18n.t "framgia_library"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def load_categories_selectbox
    @category.map{|u| [u.name, u.id]}
  end

  def number_to_vnd amount
    number_to_currency(amount, unit: I18n.t("books.vnd"),
      precision: Settings.book.number_currency, delimiter: "",
      format: Settings.book.price)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def load_review
    @book.reviews.build
  end
end

app/helpers/user_helper.rb
module UserHelper
  def select_gender
    User.genders.keys.map{|gender| [gender.titleize, gender]}
  end

  def select_role
    User.roles.keys.map{|role| [role.titleize, role]}
  end
end

app/views/admin/authors/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for [:admin, @author], remote: true do |f| %>
    <div class="modal-body">
      <ul class="errors"></ul>
      <div class="form-group">
        <%= f.label :name, class:"control-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :profile, class:"control-label" %>
        <%= f.text_field :profile, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :avatar, class: "control-label" %>
        <%= f.file_field :avatar, class: "form-control" %>
      </div>
    </div>
    <div class="modal-footer">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to t(".bnt-cancel"), "#", class: "btn", data: {dismiss: "modal"} %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/authors/_new.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h3><%= t(".title") %></h3>
  </div>
</div>
<%= render "form" %>

app/views/admin/authors/_save.js.erb
$('ul.errors').html('')
<% if @author.errors.any? %>
  <% @author.errors.full_messages.each do |message| %>
    $('ul.errors').append($('<li />').html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $('#author-modal').modal('hide')
  $('#notification-modal').html('<%= escape_javascript(render "shared/show_notification.html") %>')
  $('#notification-div').prepend('<%= j render "shared/flash" %>')
  $('#notification-modal').modal('show')
  $('#notification-modal').on('hidden.bs.modal', function () {
  location.reload();
  })
<% end %>

app/views/admin/authors/create.js.erb
<%= render "save" %>

app/views/admin/authors/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to  new_admin_author_path, remote: true,
    class: "btn btn-primary" do %>
    <span class="glyphicon glyphicon-plus"></span><%= t(".new") %>
    <% end %>
    <div class="new-product"></div>
  </div>

  <div class="input-group">
    <%= search_form_for [:admin, @search],class: "navbar-form" do |f| %>
    <%= f.text_field :name_cont, class: "form-control", value: "", placeholder: "search name ..." %>
    <%= f.text_field :id_in, class: "form-control", value: "", placeholder: " search id " %>
    <div class="input-group-btn">
      <%= button_tag class: "btn btn-default", value: "search" do %>
      <i class="glyphicon glyphicon-search"></i>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t(".tb-id") %></th>
      <th><%= t(".tb-name") %></th>
      <th><%= t(".tb-profile") %></th>
      <th><%= t(".tb-acction") %></th>
    </tr>
  </thead>
  <tbody class="author-index">
    <% @authors.each do |author| %>
    <tr>
      <td><%= author.id %></td>
      <td><%= author.name %></td>
      <td><%= author.profile %></td>
      <td>
        <%= link_to t(".show"), admin_author_path(author), remote: true %>
        &nbsp;
        <%= link_to edit_admin_author_path(author),
        remote: true do %>
        <i class="glyphicon glyphicon-wrench"></i>
        <% end %>
        &nbsp;
        <%= link_to admin_author_delete_path(author), remote: true,
        class: "delete-user" do %>
        <i class="glyphicon glyphicon-remove"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
</div>
<div id="author-modal" class="modal fade"></div>
<div id="notification-modal" class=" modal fade"></div>

app/views/admin/authors/new.js.erb
$('#author-modal').html('<%= j (render "new") %>')
$('#author-modal').modal('show')

app/views/authors/_author.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
  <div class="image-flip" ontouchstart="this.classList.toggle('hover');">
    <div class="mainflip">
      <div class="frontside">
        <div class="cards">
          <div class="card-body text-center">
            <p><img class=" avatar" src="<%= author.avatar %>" alt="card image"></p>
            <h4 class="card-title"><%= author.name %></h4>
            <p class="card-text"><%= author.profile %></p>
            <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-eye"></i></a>
          </div>
        </div>
      </div>
      <div class="backside">
        <div class="cards">
          <div class="card-body text-center mt-4">
            <h4 class="card-title"><%=link_to author.name, author %></h4>
            <p class="card-text"><%= author.profile %></p>
            <ul class="list-inline">
              <li class="list-inline-item">
                <a class="social-icon text-xs-center" target="_blank" href="#">
                    <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="social-icon text-xs-center" target="_blank" href="#">
                    <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="social-icon text-xs-center" target="_blank" href="#">
                    <i class="fa fa-skype"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="social-icon text-xs-center" target="_blank" href="#">
                    <i class="fa fa-google"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/authors/_book.html.erb
<div>
  <p class="space" ><%= t("review.space") %></p>
  <%= link_to book.name, book_path(book) %>
</div>

app/views/authors/_search.html.erb
<%= search_form_for @search, remote: true, class: "col-md-12 au" do |f| %>
  <%= f.label t("author.name") %>
  <%= f.text_field :name_cont %>
  <%= f.submit t("books.search"), class: "btn btn-primary" %>
<% end %>

app/views/authors/index.html.erb
<% provide(:title, t("author.all_author")) %>
<h1><%= t("author.all_author") %></h1>

<%= render "authors/search" %>

<%= will_paginate %>

<ul class="author" id="author-list">
  <%= render @authors %>
</ul>
<%= will_paginate %>

app/views/authors/index.js.erb
$('#author-list').html('<%= j render @authors %>');

app/views/authors/show.html.erb
<div class="container emp-profile">
  <form method="post">
    <div class="row">
      <div class="col-md-4">
       <div class="profile-img">
         <%= image_tag "/#{@author.avatar}" %>
       </div>
      </div>
      <div class="col-md-6">
        <div class="profile-head">
          <h3>
            <%= @author.name %>
          </h3>
          <button class="like btn btn-default" type="button"><%= t("author.follow") %></button>
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab " aria-controls="home" aria-selected="true"><%= t("author.profile") %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><%= t("author.book", name: @author.name) %></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="author col-md-8">
        <div class="tab-content profile-tab" id="myTabContent">
          <div class="tab-pane fade active" id="home" role="tabpanel" aria-labelledby="home-tab">
           <div class="row">
             <div class="col-md-6">
               <p><%= @author.profile %></p>
             </div>
           </div>
          </div>
          <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <div class="row">
              <div class="col-md-6">
                <p><%= render partial: "book", collection: @author.books %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>           
</div>