config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  devise_for :users
  resources :users
  root "static_pages#home"

  get "reviews/show"
  resources :books do
    resources :reviews
  end
  namespace :admin do
    resources :users do
      get "delete"
    end
    resources :books do
      get "delete"
    end
    resources :publishers do
      get "get_publisher"
    end
     resources :authors do
      get "get_author"
    end
  end
  resources :authors, only: %i(index show)
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, [User, Book]
      can :update, User, id: user.id
      can [:create, :read], [Review]
      can :destory, Review do |review|
        review.user == user
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :follows
  has_many :author_books
  has_many :books, through: :author_books

  mount_uploader :avatar, PictureUploader

  scope :newest, ->{order name: :ASC}
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  belongs_to :category
  has_many :request_details
  has_many :follows
  has_many :likes
  has_many :reviews
  has_many :author_books
  has_many :authors, through: :author_books

  mount_uploader :image, PictureUploader

  delegate :name, to: :category, prefix: :category
  delegate :name, to: :publisher, prefix: :publisher

  scope :newest, ->{order :created_at}
  accepts_nested_attributes_for :author_books

  def writers
    authors.map(&:name).join(", ")
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  scope :sort_by_name, ->{order name: :asc}
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :book
  belongs_to :author
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books

  scope :newest, ->{order created_at: :DESC}
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :requests_details
  belongs_to :user

  enum status: {pending: 0, approved: 1, cancel: 2, reject: 3}
end

app/models/request_detail.rb
class RequestDetail < ApplicationRecord
  belongs_to :book
  belongs_to :request

  enum status: {pending: 0, approved: 1, cancel: 2, reject: 3}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user

  delegate :name, to: :user, allow_nil: true

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :request
  has_many :likes
  has_many :reviews
  has_many :follows

  validates :name, presence: true

  enum role: {user: 0, admin: 1}
  enum gender: {male: 0, female: 1}

  scope :newest, ->{order name: :ASC}
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  before_action :load_publisher, except: %i(index create new)
  before_action :load_publishers, only: %i(index create update destroy)

  def index; end

  def show; end

  def get_publisher; end

  def new
    @publisher = Publisher.new
  end

  def create
    if @publisher = Publisher.create(publisher_params)
      flash[:success] = t ".msg-create"
    else
      flash[:danger] = t ".msg-error"
    end
    respond_to do |format|
      format.js {}
    end
  end

  def edit; end

  def update
    if @publisher.update_attributes(publisher_params)
      flash[:success] = t ".msg-update"
    else
      flash[:danger] = t ".msg-error"
    end
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    if @publisher.destroy
      flash[:success] = t ".msg-delete"
    else
      flash[:danger] = t ".msg-error"
    end
    respond_to do |format|
      format.js {}
    end
  end

  private

  def load_publishers
    @search = Publisher.newest.ransack params[:q]
    @publishers = @search.result.paginate page: params[:page],
      per_page: Settings.user.per_page
  end

  def load_publisher
    @publisher = Publisher.find_by id: params[:publisher_id] if
      params[:publisher_id].present?
    @publisher = Publisher.find_by id: params[:id] if params[:id].present?
    return if @publisher
    respond_to do |format|
      flash[:danger] = t(".msg-not_found")
      format.js{render partial: "not_found"}
    end
  end

  def publisher_params
    params.require(:publisher).permit :name, :address
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :load_author, only: :show

  def index
    @search = Author.ransack params[:q]
    @authors = @search.result.newest.paginate page: params[:page],
      per_page: Settings.book.per_page
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  private

  def load_author
    @author = Author.find_by id: params[:id]
    return if @author
    flash[:danger] = t "messenger.no_data"
    render :index
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: :show
  authorize_resource
  before_action :load_book, only: :show
  before_action :load_category, only: :index

  def index
    @search = Book.ransack params[:q]
    @books = @search.result.newest.paginate page: params[:page],
      per_page: Settings.book.per_page
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  private

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = t "messenger.no_data"
    render :index
  end

  def load_category
    @category = Category.sort_by_name
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_review, only: :destroy

  def show
    respond_to do |format|
      format.js
    end
  end

  def create
    @review = Review.new review_params
    if @review.save
      @book = @review.book
      flash[:success] = t "review.successful"
    else
      flash[:danger] = t "review.fails"
    end
    respond_to do |format|
      format.js {}
    end
  end

  def destroy
    if @review.destroy
      @book = @review.book
      flash[:success] = t "review.delete"
    else
      flash[:danger] = t "review.fails"
    end
    respond_to do |format|
      format.js {}
    end
  end

  private

  def review_params
    params.require(:review).permit :content, :user_id, :book_id
  end

  def load_review
    @review = Review.find_by id: params[:id]
    return if @review
    flash[:danger] = t "messenger.no_data"
    redirect_to book_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show; end
end

app/helpers/admin/publishers_helper.rb
module Admin::PublishersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = I18n.t "framgia_library"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def load_categories_selectbox
    @category.map{|u| [u.name, u.id]}
  end

  def number_to_vnd amount
    number_to_currency(amount, unit: I18n.t("books.vnd"),
      precision: Settings.book.number_currency, delimiter: "",
      format: Settings.book.price)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def load_review
    @book.reviews.build
  end
end

app/helpers/user_helper.rb
module UserHelper
  def select_gender
    User.genders.keys.map{|gender| [gender.titleize, gender]}
  end

  def select_role
    User.roles.keys.map{|role| [role.titleize, role]}
  end
end

app/views/admin/publishers/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3><%= t ".title" %></h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  <%= t ".msg-comf" %><b><%= @publisher.name %></b> ?
  </div>
  <div class="modal-footer">
    <%= link_to t(".bnt-yes"), admin_publisher_path(@publisher), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to t(".bnt_no"), "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/admin/publishers/_edit.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h3><%= t(".title") %><%= @publisher.name %></h3>
  </div>
</div>
<%= render 'form' %>

app/views/admin/publishers/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for [:admin, @publisher], remote: true do |f|  %>
       <div class = "modal-body">
        <ul class= "errors"></ul>

        <div class="form-group">
          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :address, class: "control-label" %>
          <%= f.text_field :address, class: "form-control" %>
        </div>

      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to t(".tbn-cancel"), "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/publishers/_new.html.erb
<%= render 'form' %>

app/views/admin/publishers/_not_found.js.erb
$('#publisher-modal').modal('hide')
$('#notification-modal').html('<%= j render "shared/show_notification.html" %>')
$('#notification-div').prepend('<%= j render "shared/flash" %>')
$('#notification-modal').modal('show')

app/views/admin/publishers/_publisher.html.erb
<tr>
  <td><%= publisher.id %></td>
  <td><%= publisher.name %></td>
  <td><%= publisher.address %></td>
  <td>
    <%= link_to t(".show"), admin_publisher_path(publisher), remote: true %>
    &nbsp;
    <%= link_to edit_admin_publisher_path(publisher),
      remote: true do %>
      <i class="glyphicon glyphicon-wrench"></i>
    <% end %>
    &nbsp;
    <%= link_to admin_publisher_get_publisher_path(publisher), remote: true,
      class: "delete-user" do %>
      <i class="glyphicon glyphicon-remove"></i>
    <% end %>
  </td>
</tr>

app/views/admin/publishers/_save.js.erb
$('ul.errors').html('')
<% if @publisher.errors.any? %>
  <% @publisher.errors.full_messages.each do |message| %>
    $('ul.errors').append($('<li />').html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $('#publisher-modal').modal('hide')
  $('#notification-modal').html('<%= escape_javascript(render "shared/show_notification.html") %>')
  $('#notification-div').prepend('<%= j render "shared/flash" %>')
  $('#notification-modal').modal('show')
  $('#notification-modal').on('hidden.bs.modal', function (){
    location.reload();
  })
<% end %>

app/views/admin/publishers/create.js.erb
<%= render 'save' %>

app/views/admin/publishers/destroy.js.erb
<%= render 'save' %>

app/views/admin/publishers/edit.js.erb
$('#publisher-modal').html('<%= j (render "edit") %>')
$('#publisher-modal').modal('show')

app/views/admin/publishers/get_publisher.js.erb
$('#publisher-modal').html('<%= j render "delete" %>')
$('#publisher-modal').modal('show')

app/views/admin/publishers/index.html.erb
<div class="container">
  <div class="well">
    <%= link_to  new_admin_publisher_path, remote: true,
      class: "btn btn-primary" do %>
      <span class="glyphicon glyphicon-plus"></span><%= t(".new") %>
    <% end %>
    <div class="new-product"></div>
  </div>

  <div class="input-group">
    <%= search_form_for [:admin, @search], class: "navbar-form" do |f| %>
      <%= f.text_field :name_cont, class: "form-control", value: "", placeholder: t(".msg-search_name") %>
      <%= f.text_field :id_in, class: "form-control", value: "", placeholder:t(".msg-search_id") %>
      <div class="input-group-btn">
        <%= button_tag class: "btn btn-default", value: t(".search") do %>
          <i class="glyphicon glyphicon-search"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t(".tb-id") %></th>
      <th><%= t(".tb-name") %></th>
      <th><%= t(".tb-address") %></th>
      <th><%= t(".tb-acction") %></th>
    </tr>
  </thead>
  <tbody class="publisher-index">
    <%= render @publishers %>
  </tbody>
</table>
<%= will_paginate %>
</div>
<div id="publisher-modal" class="modal fade"></div>
<div id="notification-modal" class=" modal fade"></div>

app/views/admin/publishers/new.js.erb
$('#publisher-modal').html('<%= j (render "new") %>')
$('#publisher-modal').modal('show')

app/views/admin/publishers/update.js.erb
<%= render 'save' %>