config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  devise_for :users
  resources :users
  root "static_pages#home"

  get "reviews/show"
  resources :books do
    resources :reviews
  end
  namespace :admin do
    resources :users do
      get "delete"
    end
    resources :books do
      get "delete"
    end
    resources :publishers do
      get "get_publisher"
    end
     resources :authors do
      get "get_author"
    end
  end
  resources :authors, only: %i(index show)
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, [User, Book]
      can :update, User, id: user.id
      can [:create, :read], [Review]
      can :destory, Review do |review|
        review.user == user
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :follows
  has_many :author_books
  has_many :books, through: :author_books

  mount_uploader :avatar, PictureUploader

  scope :newest, ->{order name: :ASC}
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  belongs_to :category
  has_many :request_details
  has_many :follows
  has_many :likes
  has_many :reviews
  has_many :author_books
  has_many :authors, through: :author_books

  mount_uploader :image, PictureUploader

  delegate :name, to: :category, prefix: :category
  delegate :name, to: :publisher, prefix: :publisher

  scope :newest, ->{order :created_at}
  accepts_nested_attributes_for :author_books

  def writers
    authors.map(&:name).join(", ")
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  scope :sort_by_name, ->{order name: :asc}
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :book
  belongs_to :author
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books

  scope :newest, ->{order created_at: :DESC}
end

app/models/request.rb
class Request < ApplicationRecord
  has_many :requests_details
  belongs_to :user

  enum status: {pending: 0, approved: 1, cancel: 2, reject: 3}
end

app/models/request_detail.rb
class RequestDetail < ApplicationRecord
  belongs_to :book
  belongs_to :request

  enum status: {pending: 0, approved: 1, cancel: 2, reject: 3}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user

  delegate :name, to: :user, allow_nil: true

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :request
  has_many :likes
  has_many :reviews
  has_many :follows

  validates :name, presence: true

  enum role: {user: 0, admin: 1}
  enum gender: {male: 0, female: 1}

  scope :newest, ->{order name: :ASC}
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :load_author, only: :show

  def index
    @search = Author.ransack params[:q]
    @authors = @search.result.newest.paginate page: params[:page],
      per_page: Settings.book.per_page
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  private

  def load_author
    @author = Author.find_by id: params[:id]
    return if @author
    flash[:danger] = t "messenger.no_data"
    render :index
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: :show
  authorize_resource
  before_action :load_book, only: :show
  before_action :load_category, only: :index

  def index
    @search = Book.ransack params[:q]
    @books = @search.result.newest.paginate page: params[:page],
      per_page: Settings.book.per_page
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show; end

  private

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = t "messenger.no_data"
    render :index
  end

  def load_category
    @category = Category.sort_by_name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = I18n.t "framgia_library"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def load_categories_selectbox
    @category.map{|u| [u.name, u.id]}
  end

  def number_to_vnd amount
    number_to_currency(amount, unit: I18n.t("books.vnd"),
      precision: Settings.book.number_currency, delimiter: "",
      format: Settings.book.price)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def load_review
    @book.reviews.build
  end
end

app/helpers/user_helper.rb
module UserHelper
  def select_gender
    User.genders.keys.map{|gender| [gender.titleize, gender]}
  end

  def select_role
    User.roles.keys.map{|role| [role.titleize, role]}
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small class="created_by">
    <%= raw t("footer.created_by",
      href1: link_to(t("framgia_library"), t("footer.link_framgia")),
      href2: link_to(t("footer.name"), t("footer.link_name"))) %>
  </small>
  <nav>
    <ul class="hotline">
      <li><%= t "footer.hot_line" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("framgia_library"), root_path, id: "logo" %>
    <ul class="nav navbar-nav ">
        <li class="dropdown">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
                <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
                  <%= t ".for_admin" %><b class="caret"></b>
                <% end %>
                <ul class="dropdown-menu">
                  <li><%= link_to t(".mn-users"),  admin_users_path %></li>
                  <li><%= link_to t(".mn-books"),  admin_books_path %></li>
                  <li><%= link_to t(".mn-publishers"),  admin_publishers_path %></li>
                  <li><%= link_to t(".mn-author"),  "#" %></li>
                </ul>
            <% end %>
          <% end %>
        </li>
    </ul>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("root"), root_path %></li>
        <li><%= link_to t("book"), books_path %></li>
        <li><%= link_to t("header_author"), authors_path %></li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li><%= link_to t("manager"), admin_users_path %></li>
          <% end %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">
              <%= t("user.account", name: current_user.name) %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("user.profile"), current_user %></li>
              <li><%= link_to t("user.settings"), edit_user_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("user.log_out"), destroy_user_session_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("user.log_in"), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= "#{key}" %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_show_notification.html.erb
<div class="modal-dialog">
  <div class="modal-content">

    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title"><%= t(".title") %></h4>
    </div>

    <div class="modal-body">
      <smal id= "notification-div"></smal>
    </div>

  </div>
</div>